name: Run E2E Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: e2e
          POSTGRES_PASSWORD: e2e_password
          POSTGRES_DB: apisolid

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm ci
      
      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: postgresql://e2e:e2e_password@localhost:5432/apisolid?schema=public

